Fix answers not changing value from 'correct' to anything else.
ucfopen/enigma-materia-widget pull request #1
Opened 2019-01-02 17:41 UTC by FrenjaminBanklin

Closes #1187.

Correctly unsets 'options.correct' on answers when value is set below 100.

Also cleaned up some tests that were failing due to prior changes.

2019-01-03 17:40 UTC, clpetersonucf requested changes
LGTM once that extra console.log is snipped

2019-01-03 17:40 UTC, clpetersonucf commented on src/controllers/creator.coffee
> +			console.log answer.options.correct, answer.value
left a console.log in here

2019-01-03 17:46 UTC, clpetersonucf approved these changes

2019-01-03 17:46 UTC, clpetersonucf commented
:+1:

2019-01-09 15:58 UTC, iturgeon approved these changes
couldn't cause any issues here, and we need them tests

2019-01-09 15:59 UTC, merged