made enigma keyboard accessible
ucfopen/enigma-materia-widget pull request #13
Opened 2020-04-02 15:42 UTC by kywoodland

Before, it was impossible to tab into the widget with the keyboard, but now i've added tabindex to the appropriate elements and added functions to show/hide tabindex depending on which "screen" the user is on (so they can't tab hidden elements).

2020-04-08 18:01 UTC, iturgeon requested changes
DO IT

2020-04-08 18:01 UTC, iturgeon commented on src/controllers/player.coffee
> +	$scope.checkTab = true
OMG

2020-04-08 18:01 UTC, iturgeon commented on src/controllers/player.coffee
> +		for item in document.getElementsByClassName('question')
IDK, maybe this could be better

2020-04-08 20:59 UTC, clpetersonucf requested changes
This is good so far!! I have a handful of suggestions, just to improve usability.

First off, this is totally playable now. These suggestions are more about improving awareness of the state of the widget at any given time.

- The initial tab into the widget brings right directly to the first item on the first row. It might be handy to have an a hidden element that serves as the first tab index with an `aria-label` that provides instructions, or simply add it to the title of the widget, so users initially know what's going on ("Widget name" followed by "Questions are sorted into categories. Begin by tabbing through and responding to each question within each category", etc.)
- Grid items should probably announce what category they belong to, because right now that's not spoken to the user I don't think. "Animated TV: Question 1" and perhaps the state, if it's been answered ("Correct" or "Incorrect")
- Within individual questions, tabbing through the multiple choice responses works great, but again it might be beneficial to announce which one you've selected. Similarly, once an item has been selected and you tab to "Submit final answer", announcing the new state once you return to the question grid could be handy. ("You've answered 5 of 9 questions", etc.)

`aria-live` is great for this, because you can change the content of a single aria-live element and it immediately is spoken to the user regardless of what they're focused on within the DOM. It's great for state-related feedback that doesn't necessarily belong within an `aria-label` on every element.

2020-04-28 18:53 UTC, kywoodland commented
Updated the things based on Corey's comment:

1. Added a quick introduction that the screen reader reads when tabbed into the widget, directly after the welcome heading
2. For every question on the game board, the screen reader says the category and the question number, and if it's answered or correct/incorrect
3. If a user selects the question using the screen reader select buttons (spacebar for Voice Over, for example) it announces which was selected. And then reads back how many questions are remaining

Also:

- added live feedback via screen reader, so the user immediately knows if their answer was correct or what the correct answer was (or if they were partially correct)
- fixed the issue of the screen reader repeating the "Questions Remaining" twice
- got rid of some redundancies so the user doesn't have to tab through the same element 3 times to get to the next one, as was the case with each category

2020-05-08 15:23 UTC, clpetersonucf reviewed
This is already very usable! There's just a few final things that seem a little off, at least when using ChromeVox:

- If I tab into the widget, it focuses the header that says "welcome to Enigma!", but I haven't been able to navigate to the instructions after that. The only way seems to be to go forward with the arrow keys (down or right), then backtrack to focus the instructions. What if we combined the instructions with the "welcome to enigma!" label?

- I'm not noticing the aria-live region ever being spoken, either after choosing an answer, submitting it, or returning to the game board. Does it work with other screen readers?

- This is really minor, but there's no submit option prior to completing the widget - and when the final question is answered, the existing dom is basically replaced by the submit button. If I was unable to see what was happening on the screen, I might be a little confused. We should probably either add an aria-live update to announce what happened "You completed all questions, you scored 9 out of 9 correct, select submit to go to the score screen" or maybe stay on the game board and have a submit option available after the game board element.

2021-01-11 19:04 UTC, clpetersonucf approved these changes
I think we're good.

2021-01-11 19:13 UTC, merged